[[redirects]]
  # This rule only applies when the Host header matches the custom domain
  host = "www.simplyyousurabhi.org"
  from = "/*"
  to = "/index.html" # Assuming your Flutter index is the entry point
  status = 200
  force = true
