name: flashzone_web
description: "FlashZone Web"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  calendar_view: ^1.2.0
  cloud_firestore: ^5.4.0
  context_menus: ^2.0.0+1
  cupertino_icons: ^1.0.8
  datetime_picker_formfield_new: ^2.1.0
  detectable_text_field: ^3.0.2
  easy_sidemenu: ^0.6.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.9.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_widget_from_html_core: ^0.15.2
  fwfh_webview: ^0.15.3
  geocode: ^1.0.3
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.30
  geolocator: ^12.0.0
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+3
  #hashtagable: ^2.3.0+1
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  pdfx: ^2.6.0
  provider: ^6.1.2
  random_date: ^0.0.7
  razorpay_flutter: ^1.4.0
  razorpay_web: ^3.0.0
  riverpod: ^2.5.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dependency_overrides:
  intl: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/cinzel/Cinzel-VariableFont_wght.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-VariableFont_opsz,wdth,wght.ttf
        - asset: assets/fonts/merriweather/Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf
          style: italic
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/profile_pic_placeholder.png
    - assets/flashzoneR.png
    - assets/event_placeholder.jpeg
    - assets/google-icon.png
    - assets/logo.png
    - assets/yt_logo_fullcolor_white_digital.png
